name: Nix flake update PR

on:
  workflow_dispatch:
  schedule:
    # first of the week at 00:00 UTC
    - cron: "00 00 * * 0"

jobs:
  update-nix-flake:
    name: nix flake update and test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: setup nix
        uses: ./.github/actions/nix-setup

      - name: update nix flake inputs
        run: |
          nix flake update
          git status

      - name: run tests with nix
        uses: ./.github/actions/nix-test

      # requires allowing PRs from github actions: https://github.com/peter-evans/create-pull-request?tab=readme-ov-file#workflow-permissions
      - name: create pull request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 #v8
        with:
          branch: update-nix-flake
          title: "[BOT] Weekly flake.nix update"
          commit-message: "chore: weekly flake.nix update"
          body: |
            Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request).
          labels: maintenance
